title: "Alex Mwathi – Cybersecurity Portfolio"
description: "Ethical Hacking | Penetration Testing | Security Research"
url: "https://mwathi-alex.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Author Information
author:
  name: "Alex Mwathi"
  avatar: "/assets/images/profile.jpg"   # Upload later
  bio: "Cisco Ethical Hacker | ISC² Certified | Offensive Security Enthusiast"
  location: "Remote / On-site"
  links:
    - label: "Resume"
      icon: "fas fa-file-pdf"
      url: "/assets/CV.pdf"              # Upload later
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Mwathi-alex"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
