title: "ALEX MWATHI"
email: alexmwathi6@gmail.com
description: >-
  Junior PenTester | Quality services in assuring cybersecurity
twitter_username: alexmwathi
github_username: Mwathi-alex
minimal_mistakes_skin: "dark"
search: true

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "ALEX MWATHI"
  avatar : "/assets/images/portraitpic.jpg"
  bio    : "Quality services in assuring cybersecurity"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://yourwebsite.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/alexmwathi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Mwathi-alex"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/yourprofile"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/alexmwathi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Mwathi-alex"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/yourprofile"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
